export const CITIES = [
  // --- INDIA (100 CITIES) ---
  { id: "delhi", name: "Delhi", region: "India", currency: "INR" },
  { id: "mumbai", name: "Mumbai", region: "India", currency: "INR" },
  { id: "bengaluru", name: "Bengaluru", region: "India", currency: "INR" },
  { id: "hyderabad", name: "Hyderabad", region: "India", currency: "INR" },
  { id: "pune", name: "Pune", region: "India", currency: "INR" },
  { id: "chennai", name: "Chennai", region: "India", currency: "INR" },
  { id: "kolkata", name: "Kolkata", region: "India", currency: "INR" },
  { id: "gurugram", name: "Gurugram", region: "India", currency: "INR" },
  { id: "noida", name: "Noida", region: "India", currency: "INR" },
  { id: "ahmedabad", name: "Ahmedabad", region: "India", currency: "INR" },
  { id: "jaipur", name: "Jaipur", region: "India", currency: "INR" },
  { id: "lucknow", name: "Lucknow", region: "India", currency: "INR" },
  { id: "surat", name: "Surat", region: "India", currency: "INR" },
  { id: "indore", name: "Indore", region: "India", currency: "INR" },
  { id: "chandigarh", name: "Chandigarh", region: "India", currency: "INR" },
  { id: "kochi", name: "Kochi", region: "India", currency: "INR" },
  { id: "visakhapatnam", name: "Visakhapatnam", region: "India", currency: "INR" },
  { id: "bhopal", name: "Bhopal", region: "India", currency: "INR" },
  { id: "patna", name: "Patna", region: "India", currency: "INR" },
  { id: "vadodara", name: "Vadodara", region: "India", currency: "INR" },
  { id: "ghaziabad", name: "Ghaziabad", region: "India", currency: "INR" },
  { id: "ludhiana", name: "Ludhiana", region: "India", currency: "INR" },
  { id: "agra", name: "Agra", region: "India", currency: "INR" },
  { id: "nashik", name: "Nashik", region: "India", currency: "INR" },
  { id: "faridabad", name: "Faridabad", region: "India", currency: "INR" },
  { id: "meerut", name: "Meerut", region: "India", currency: "INR" },
  { id: "rajkot", name: "Rajkot", region: "India", currency: "INR" },
  { id: "varanasi", name: "Varanasi", region: "India", currency: "INR" },
  { id: "srinagar", name: "Srinagar", region: "India", currency: "INR" },
  { id: "amritsar", name: "Amritsar", region: "India", currency: "INR" },
  { id: "navi-mumbai", name: "Navi Mumbai", region: "India", currency: "INR" },
  { id: "ranchi", name: "Ranchi", region: "India", currency: "INR" },
  { id: "coimbatore", name: "Coimbatore", region: "India", currency: "INR" },
  { id: "jabalpur", name: "Jabalpur", region: "India", currency: "INR" },
  { id: "gwalior", name: "Gwalior", region: "India", currency: "INR" },
  { id: "howrah", name: "Howrah", region: "India", currency: "INR" },
  { id: "vijayawada", name: "Vijayawada", region: "India", currency: "INR" },
  { id: "jodhpur", name: "Jodhpur", region: "India", currency: "INR" },
  { id: "madurai", name: "Madurai", region: "India", currency: "INR" },
  { id: "guwahati", name: "Guwahati", region: "India", currency: "INR" },
  { id: "raipur", name: "Raipur", region: "India", currency: "INR" },
  { id: "kota", name: "Kota", region: "India", currency: "INR" },
  { id: "solapur", name: "Solapur", region: "India", currency: "INR" },
  { id: "bareilly", name: "Bareilly", region: "India", currency: "INR" },
  { id: "moradabad", name: "Moradabad", region: "India", currency: "INR" },
  { id: "mysore", name: "Mysore", region: "India", currency: "INR" },
  { id: "tiruchirappalli", name: "Tiruchirappalli", region: "India", currency: "INR" },
  { id: "hubli-dharwad", name: "Hubballi-Dharwad", region: "India", currency: "INR" },
  { id: "aligarh", name: "Aligarh", region: "India", currency: "INR" },
  { id: "jalandhar", name: "Jalandhar", region: "India", currency: "INR" },
  { id: "bhubaneswar", name: "Bhubaneswar", region: "India", currency: "INR" },
  { id: "salem", name: "Salem", region: "India", currency: "INR" },
  { id: "warangal", name: "Warangal", region: "India", currency: "INR" },
  { id: "guntur", name: "Guntur", region: "India", currency: "INR" },
  { id: "bhiwandi", name: "Bhiwandi", region: "India", currency: "INR" },
  { id: "saharanpur", name: "Saharanpur", region: "India", currency: "INR" },
  { id: "gorakhpur", name: "Gorakhpur", region: "India", currency: "INR" },
  { id: "bikaner", name: "Bikaner", region: "India", currency: "INR" },
  { id: "amravati", name: "Amravati", region: "India", currency: "INR" },
  { id: "jamshedpur", name: "Jamshedpur", region: "India", currency: "INR" },
  { id: "bhilai", name: "Bhilai", region: "India", currency: "INR" },
  { id: "cuttack", name: "Cuttack", region: "India", currency: "INR" },
  { id: "firozabad", name: "Firozabad", region: "India", currency: "INR" },
  { id: "nellore", name: "Nellore", region: "India", currency: "INR" },
  { id: "bhavnagar", name: "Bhavnagar", region: "India", currency: "INR" },
  { id: "dehradun", name: "Dehradun", region: "India", currency: "INR" },
  { id: "durgapur", name: "Durgapur", region: "India", currency: "INR" },
  { id: "asansol", name: "Asansol", region: "India", currency: "INR" },
  { id: "rourkela", name: "Rourkela", region: "India", currency: "INR" },
  { id: "nanded", name: "Nanded", region: "India", currency: "INR" },
  { id: "kolhapur", name: "Kolhapur", region: "India", currency: "INR" },
  { id: "ajmer", name: "Ajmer", region: "India", currency: "INR" },
  { id: "akola", name: "Akola", region: "India", currency: "INR" },
  { id: "gulbarga", name: "Gulbarga", region: "India", currency: "INR" },
  { id: "jamnagar", name: "Jamnagar", region: "India", currency: "INR" },
  { id: "ujjain", name: "Ujjain", region: "India", currency: "INR" },
  { id: "siliguri", name: "Siliguri", region: "India", currency: "INR" },
  { id: "jhansi", name: "Jhansi", region: "India", currency: "INR" },
  { id: "ulhasnagar", name: "Ulhasnagar", region: "India", currency: "INR" },
  { id: "sangli", name: "Sangli", region: "India", currency: "INR" },
  { id: "jammu", name: "Jammu", region: "India", currency: "INR" },
  { id: "belgaum", name: "Belgaum", region: "India", currency: "INR" },
  { id: "mangalore", name: "Mangalore", region: "India", currency: "INR" },
  { id: "tirunelveli", name: "Tirunelveli", region: "India", currency: "INR" },
  { id: "malegaon", name: "Malegaon", region: "India", currency: "INR" },
  { id: "udaipur", name: "Udaipur", region: "India", currency: "INR" },
  { id: "gaya", name: "Gaya", region: "India", currency: "INR" },
  { id: "tiruppur", name: "Tiruppur", region: "India", currency: "INR" },
  { id: "davangere", name: "Davangere", region: "India", currency: "INR" },
  { id: "kozhikode", name: "Kozhikode", region: "India", currency: "INR" },
  { id: "akola", name: "Akola", region: "India", currency: "INR" },
  { id: "kurnool", name: "Kurnool", region: "India", currency: "INR" },
  { id: "rajamahendravaram", name: "Rajamahendravaram", region: "India", currency: "INR" },
  { id: "bokaro", name: "Bokaro", region: "India", currency: "INR" },
  { id: "south-delhi", name: "South Delhi", region: "India", currency: "INR" },
  { id: "dwarka", name: "Dwarka", region: "India", currency: "INR" },
  { id: "vashi", name: "Vashi", region: "India", currency: "INR" },
  { id: "andheri", name: "Andheri", region: "India", currency: "INR" },
  { id: "whitefield", name: "Whitefield", region: "India", currency: "INR" },
  { id: "hitech-city", name: "HITEC City", region: "India", currency: "INR" },

  // --- GLOBAL (100 CITIES) ---
  { id: "new-york", name: "New York", region: "USA", currency: "USD" },
  { id: "london", name: "London", region: "UK", currency: "GBP" },
  { id: "dubai", name: "Dubai", region: "UAE", currency: "USD" },
  { id: "singapore", name: "Singapore", region: "Singapore", currency: "USD" },
  { id: "paris", name: "Paris", region: "France", currency: "EUR" },
  { id: "berlin", name: "Berlin", region: "Germany", currency: "EUR" },
  { id: "tokyo", name: "Tokyo", region: "Japan", currency: "USD" },
  { id: "sydney", name: "Sydney", region: "Australia", currency: "AUD" },
  { id: "san-francisco", name: "San Francisco", region: "USA", currency: "USD" },
  { id: "austin", name: "Austin", region: "USA", currency: "USD" },
  { id: "seattle", name: "Seattle", region: "USA", currency: "USD" },
  { id: "los-angeles", name: "Los Angeles", region: "USA", currency: "USD" },
  { id: "chicago", name: "Chicago", region: "USA", currency: "USD" },
  { id: "toronto", name: "Toronto", region: "Canada", currency: "CAD" },
  { id: "vancouver", name: "Vancouver", region: "Canada", currency: "CAD" },
  { id: "amsterdam", name: "Amsterdam", region: "Netherlands", currency: "EUR" },
  { id: "munich", name: "Munich", region: "Germany", currency: "EUR" },
  { id: "zurich", name: "Zurich", region: "Switzerland", currency: "CHF" },
  { id: "geneva", name: "Geneva", region: "Switzerland", currency: "CHF" },
  { id: "hong-kong", name: "Hong Kong", region: "Hong Kong", currency: "USD" },
  { id: "seoul", name: "Seoul", region: "South Korea", currency: "USD" },
  { id: "shanghai", name: "Shanghai", region: "China", currency: "USD" },
  { id: "beijing", name: "Beijing", region: "China", currency: "USD" },
  { id: "boston", name: "Boston", region: "USA", currency: "USD" },
  { id: "philadelphia", name: "Philadelphia", region: "USA", currency: "USD" },
  { id: "atlanta", name: "Atlanta", region: "USA", currency: "USD" },
  { id: "denver", name: "Denver", region: "USA", currency: "USD" },
  { id: "salt-lake-city", name: "Salt Lake City", region: "USA", currency: "USD" },
  { id: "portland", name: "Portland", region: "USA", currency: "USD" },
  { id: "las-vegas", name: "Las Vegas", region: "USA", currency: "USD" },
  { id: "phoenix", name: "Phoenix", region: "USA", currency: "USD" },
  { id: "houston", name: "Houston", region: "USA", currency: "USD" },
  { id: "washington-dc", name: "Washington DC", region: "USA", currency: "USD" },
  { id: "dublin", name: "Dublin", region: "Ireland", currency: "EUR" },
  { id: "stockholm", name: "Stockholm", region: "Sweden", currency: "EUR" },
  { id: "copenhagen", name: "Copenhagen", region: "Denmark", currency: "EUR" },
  { id: "oslo", name: "Oslo", region: "Norway", currency: "EUR" },
  { id: "helsinki", name: "Helsinki", region: "Finland", currency: "EUR" },
  { id: "madrid", name: "Madrid", region: "Spain", currency: "EUR" },
  { id: "barcelona", name: "Barcelona", region: "Spain", currency: "EUR" },
  { id: "milan", name: "Milan", region: "Italy", currency: "EUR" },
  { id: "rome", name: "Rome", region: "Italy", currency: "EUR" },
  { id: "prague", name: "Prague", region: "Czech Republic", currency: "EUR" },
  { id: "vienna", name: "Vienna", region: "Austria", currency: "EUR" },
  { id: "warsaw", name: "Warsaw", region: "Poland", currency: "EUR" },
  { id: "budapest", name: "Budapest", region: "Hungary", currency: "EUR" },
  { id: "istanbul", name: "Istanbul", region: "Turkey", currency: "USD" },
  { id: "tel-aviv", name: "Tel Aviv", region: "Israel", currency: "USD" },
  { id: "abu-dhabi", name: "Abu Dhabi", region: "UAE", currency: "USD" },
  { id: "riyadh", name: "Riyadh", region: "Saudi Arabia", currency: "USD" },
  { id: "doha", name: "Doha", region: "Qatar", currency: "USD" },
  { id: "kuwait-city", name: "Kuwait City", region: "Kuwait", currency: "USD" },
  { id: "johannesburg", name: "Johannesburg", region: "South Africa", currency: "USD" },
  { id: "cape-town", name: "Cape Town", region: "South Africa", currency: "USD" },
  { id: "nairobi", name: "Nairobi", region: "Kenya", currency: "USD" },
  { id: "lagos", name: "Lagos", region: "Nigeria", currency: "USD" },
  { id: "cairo", name: "Cairo", region: "Egypt", currency: "USD" },
  { id: "bangkok", name: "Bangkok", region: "Thailand", currency: "USD" },
  { id: "kuala-lumpur", name: "Kuala Lumpur", region: "Malaysia", currency: "USD" },
  { id: "ho-chi-minh-city", name: "Ho Chi Minh City", region: "Vietnam", currency: "USD" },
  { id: "manila", name: "Manila", region: "Philippines", currency: "USD" },
  { id: "jakarta", name: "Jakarta", region: "Indonesia", currency: "USD" },
  { id: "melbourne", name: "Melbourne", region: "Australia", currency: "AUD" },
  { id: "auckland", name: "Auckland", region: "New Zealand", currency: "USD" },
  { id: "wellington", name: "Wellington", region: "New Zealand", currency: "USD" },
  { id: "montreal", name: "Montreal", region: "Canada", currency: "CAD" },
  { id: "calgary", name: "Calgary", region: "Canada", currency: "CAD" },
  { id: "ottawa", name: "Ottawa", region: "Canada", currency: "CAD" },
  { id: "mexico-city", name: "Mexico City", region: "Mexico", currency: "USD" },
  { id: "sao-paulo", name: "Sao Paulo", region: "Brazil", currency: "USD" },
  { id: "rio-de-janeiro", name: "Rio de Janeiro", region: "Brazil", currency: "USD" },
  { id: "buenos-aires", name: "Buenos Aires", region: "Argentina", currency: "USD" },
  { id: "santiago", name: "Santiago", region: "Chile", currency: "USD" },
  { id: "bogota", name: "Bogota", region: "Colombia", currency: "USD" },
  { id: "lima", name: "Lima", region: "Peru", currency: "USD" },
  { id: "lisbon", name: "Lisbon", region: "Portugal", currency: "EUR" },
  { id: "moscow", name: "Moscow", region: "Russia", currency: "USD" },
  { id: "brussels", name: "Brussels", region: "Belgium", currency: "EUR" },
  { id: "luxembourg", name: "Luxembourg", region: "Luxembourg", currency: "EUR" },
  { id: "athens", name: "Athens", region: "Greece", currency: "EUR" },
  { id: "bucharest", name: "Bucharest", region: "Romania", currency: "EUR" },
  { id: "sofia", name: "Sofia", region: "Bulgaria", currency: "EUR" },
  { id: "belgrade", name: "Belgrade", region: "Serbia", currency: "EUR" },
  { id: "zagreb", name: "Zagreb", region: "Croatia", currency: "EUR" },
  { id: "bratislava", name: "Bratislava", region: "Slovakia", currency: "EUR" },
  { id: "manchester", name: "Manchester", region: "UK", currency: "GBP" },
  { id: "birmingham", name: "Birmingham", region: "UK", currency: "GBP" },
  { id: "glasgow", name: "Glasgow", region: "UK", currency: "GBP" },
  { id: "barcelona", name: "Barcelona", region: "Spain", currency: "EUR" },
  { id: "frankfurt", name: "Frankfurt", region: "Germany", currency: "EUR" },
  { id: "hamburg", name: "Hamburg", region: "Germany", currency: "EUR" },
  { id: "lyon", name: "Lyon", region: "France", currency: "EUR" },
  { id: "marseille", name: "Marseille", region: "France", currency: "EUR" },
  { id: "osaka", name: "Osaka", region: "Japan", currency: "USD" },
  { id: "fukuoka", name: "Fukuoka", region: "Japan", currency: "USD" },
  { id: "nagoya", name: "Nagoya", region: "Japan", currency: "USD" },
  { id: "pert", name: "Perth", region: "Australia", currency: "AUD" },
  { id: "brisbane", name: "Brisbane", region: "Australia", currency: "AUD" },
  { id: "adelaide", name: "Adelaide", region: "Australia", currency: "AUD" },
];
